default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: 127.0.0.1
  port: 5435

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "bags_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "bags_test" } %>
